### ISSUE TITLE
No longer stops the nag

### ISSUE THREAD

**Issue by Ryan659** [ksaanen/WebExt.Reddit.Annoyances#10]
The nag to use the Reddit app has appeared again. Using the latest Firefox on Android.

**Comment by ksaanen** [comment]
Thanks for reporting Ryan, I'll go have a look.

**Comment by ksaanen** [comment]
Still not fixed in version 1.2.1 it seems, will have to take a better look.

**Comment by ksaanen** [comment]
@Ryan659 issue is solved now, the update should roll out to you automatically within the next 24 hours. Enjoy :)

**Comment by Ryan659** [comment]
Updated manually and looks to be fixed. 

Thanks!
