### ISSUE TITLE
Set header to scroll with the rest of the content.

### ISSUE THREAD

**Issue by ksaanen** [ksaanen/WebExt.Reddit.Annoyances#4]
Make optional on settings

**Comment by ksaanen** [comment]
Added in version 1.1.0

**Comment by DejayRezme** [comment]
Thank you so much for making this. 
Without alternative reddit apps addons like this are the only way to continue using reddit.

**Comment by ksaanen** [comment]
> Thank you so much for making this. Without alternative reddit apps addons like this are the only way to continue using reddit.

Thank you for the nice feedback :)
